[package]
name = "plebscript-fastly"
version = "0.1.0-dev"
authors = []
edition = "2018"
publish = false

[profile.release]
debug = 1

[dependencies]
fastly = "0.10"
include_dir = "0.7"
plebscript = { path = "../" }
